from collections.abc import Callable
from pathlib import Path
from urllib.parse import urlencode

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse

from ...config import Settings
from ...files import (
    discover_session_files,
    native_browser_headers,
    native_browser_media_type,
    read_session_messages,
    resolve_chat_file,
)
from ...pi_rpc import PiRpcError, PiRuntimeManager
from ...store import Store

MARKDOWN_EXTENSIONS = {".md", ".markdown"}


def artifact_share_url(token: str, path: str) -> str:
    query = urlencode({"share": token, "path": path, "from": "chat"})
    return f"/file-view?{query}"


def create_router(
    settings: Settings,
    store: Store,
    runtime: PiRuntimeManager,
    visible_or_404: Callable[[dict | None, Request, str], dict],
    user_id: Callable[[Request], str],
    has_session_file: Callable[[dict], bool],
    visible_messages: Callable[[list[dict], str], list[dict]],
) -> APIRouter:
    router = APIRouter(prefix="/api", tags=["shares"])

    @router.post("/chats/{chat_id}/share")
    async def create_chat_share(chat_id: str, request: Request):
        chat = visible_or_404(store.get_chat(chat_id), request, "Chat")
        existing = store.get_chat_share(chat_id)
        share = store.create_share(chat_id, user_id=chat.get("user_id"))
        return {
            "token": share["token"],
            "url": f"/share/{share['token']}",
            "existing": bool(existing),
        }

    @router.get("/chats/{chat_id}/share")
    async def get_chat_share(chat_id: str, request: Request):
        visible_or_404(store.get_chat(chat_id), request, "Chat")
        share = store.get_chat_share(chat_id)
        if not share:
            raise HTTPException(404, "Share not found")
        return {"token": share["token"], "url": f"/share/{share['token']}"}

    @router.get("/chats/{chat_id}/artifact-shares")
    async def get_chat_artifact_share(chat_id: str, path: str, request: Request):
        visible_or_404(store.get_chat(chat_id), request, "Chat")
        share = store.get_chat_artifact_share(chat_id, path)
        if not share:
            raise HTTPException(404, "Artifact share not found")
        return {
            "token": share["token"],
            "path": share["path"],
            "artifact_type": share["artifact_type"],
            "url": artifact_share_url(share["token"], share["path"]),
        }

    @router.post("/chats/{chat_id}/artifact-shares")
    async def create_chat_artifact_share(chat_id: str, path: str, request: Request):
        chat = visible_or_404(store.get_chat(chat_id), request, "Chat")
        if Path(path).suffix.lower() not in MARKDOWN_EXTENSIONS:
            raise HTTPException(415, "Only Markdown artifacts can be shared")
        session_file = runtime.newest_session_file(chat)
        messages = read_session_messages(session_file) if session_file else []
        file_path = resolve_chat_file(messages, settings.pi_cwd, path)
        if not file_path:
            raise HTTPException(404, "File not found or not generated by this chat")
        existing = store.get_chat_artifact_share(chat_id, path)
        share = store.create_artifact_share(
            chat_id,
            path,
            user_id=chat.get("user_id"),
            artifact_type="markdown",
        )
        return {
            "token": share["token"],
            "path": share["path"],
            "artifact_type": share["artifact_type"],
            "url": artifact_share_url(share["token"], share["path"]),
            "existing": bool(existing),
        }

    @router.get("/shares")
    async def list_shares(request: Request):
        records = []
        for share in store.list_shares(user_id(request)):
            chat = store.get_chat(share["chat_id"])
            if chat:
                records.append(
                    {
                        "token": share["token"],
                        "chat_id": chat["id"],
                        "title": chat.get("title") or "New conversation",
                        "created_at": share["created_at"],
                        "kind": "session",
                        "url": f"/share/{share['token']}",
                    }
                )
        for share in store.list_artifact_shares(user_id(request)):
            chat = store.get_chat(share["chat_id"])
            if chat:
                records.append(
                    {
                        "token": share["token"],
                        "chat_id": chat["id"],
                        "title": chat.get("title") or "New conversation",
                        "created_at": share["created_at"],
                        "kind": "artifact",
                        "artifact_type": share["artifact_type"],
                        "path": share["path"],
                        "url": artifact_share_url(share["token"], share["path"]),
                    }
                )
        records.sort(key=lambda item: item.get("created_at", ""), reverse=True)
        return {"shares": records}

    @router.delete("/shares/{token}")
    async def delete_share(token: str, request: Request):
        deleted = store.delete_share(
            token, user_id(request)
        ) or store.delete_artifact_share(token, user_id(request))
        if not deleted:
            raise HTTPException(404, "Share not found")
        return {"ok": True, "token": token}

    @router.get("/share/{token}")
    async def get_shared_chat(token: str, request: Request):
        share = store.get_share(token)
        if not share:
            raise HTTPException(404, "Share not found")
        viewer = getattr(request.state, "user", None)
        chat = store.get_chat(share["chat_id"])
        if not chat:
            raise HTTPException(404, "Share not found")
        if chat["status"] != "created" and has_session_file(chat):
            try:
                messages = await runtime.messages(chat)
            except PiRpcError as exc:
                raise HTTPException(503, str(exc)) from exc
        else:
            messages = []
        return {
            "chat": {
                "title": chat.get("title"),
                "created_at": chat.get("created_at"),
                "updated_at": chat.get("updated_at"),
                "agent_id": chat.get("agent_id"),
            },
            "messages": visible_messages(messages, "production"),
            # The shared page shows a revoke control only to the account that owns
            # the link; anonymous readers and other accounts never see it.
            "can_manage": bool(viewer) and share.get("user_id") == viewer["id"],
        }

    @router.get("/share/{token}/files")
    async def list_shared_chat_files(token: str):
        share = store.get_share(token)
        if not share:
            raise HTTPException(404, "Share not found")
        chat = store.get_chat(share["chat_id"])
        if not chat:
            raise HTTPException(404, "Share not found")
        session_file = runtime.newest_session_file(chat)
        files = (
            discover_session_files(session_file, settings.pi_cwd)
            if session_file
            else []
        )
        return {"files": files}

    @router.get("/share/{token}/files/content")
    async def get_shared_chat_file(token: str, path: str):
        artifact_share = store.get_artifact_share(token)
        if artifact_share:
            if artifact_share.get("path") != path:
                raise HTTPException(404, "Share not found")
            if artifact_share.get("artifact_type") != "markdown":
                raise HTTPException(404, "Share not found")
            share = artifact_share
        else:
            share = store.get_share(token)
            if not share:
                raise HTTPException(404, "Share not found")
        chat = store.get_chat(share["chat_id"])
        if not chat:
            raise HTTPException(404, "Share not found")
        session_file = runtime.newest_session_file(chat)
        messages = read_session_messages(session_file) if session_file else []
        file_path = resolve_chat_file(messages, settings.pi_cwd, path)
        if not file_path:
            raise HTTPException(404, "File not found or not generated by this chat")
        if artifact_share and file_path.suffix.lower() not in MARKDOWN_EXTENSIONS:
            raise HTTPException(404, "Share not found")
        try:
            content = file_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            raise HTTPException(415, "File is not a readable UTF-8 text file") from exc
        return {"content": content}

    @router.get("/share/{token}/files/view")
    async def view_shared_chat_file(token: str, path: str):
        share = store.get_share(token)
        if not share:
            raise HTTPException(404, "Share not found")
        chat = store.get_chat(share["chat_id"])
        if not chat:
            raise HTTPException(404, "Share not found")
        session_file = runtime.newest_session_file(chat)
        messages = read_session_messages(session_file) if session_file else []
        file_path = resolve_chat_file(messages, settings.pi_cwd, path)
        if not file_path:
            raise HTTPException(404, "File not found or not generated by this chat")
        media_type = native_browser_media_type(file_path)
        if not media_type:
            raise HTTPException(415, "File type is not supported for browser view")
        return FileResponse(
            file_path,
            filename=file_path.name,
            media_type=media_type,
            content_disposition_type="inline",
            headers=native_browser_headers(media_type),
        )

    return router
