"""Stable API error codes shared by the backend and frontend."""

import re
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ErrorDefinition:
    code: str
    message: str


# Keep this catalog small and stable. The English message is retained in API
# responses for compatibility; clients should translate using ``code``.
ERROR_CODES: dict[str, ErrorDefinition] = {
    "auth.required": ErrorDefinition("auth.required", "Authentication required"),
    "auth.adminRequired": ErrorDefinition(
        "auth.adminRequired", "Admin access required"
    ),
    "auth.invalidCredentials": ErrorDefinition(
        "auth.invalidCredentials", "Invalid username or password"
    ),
    "auth.usernameExists": ErrorDefinition(
        "auth.usernameExists", "Username already exists"
    ),
    "auth.userNotFound": ErrorDefinition("auth.userNotFound", "User not found"),
    "auth.adminCannotDisable": ErrorDefinition(
        "auth.adminCannotDisable", "The admin account cannot be disabled"
    ),
    "auth.adminCannotDelete": ErrorDefinition(
        "auth.adminCannotDelete", "The admin account cannot be deleted"
    ),
    "chat.titleEmpty": ErrorDefinition("chat.titleEmpty", "Chat title cannot be empty"),
    "chat.notFound": ErrorDefinition("chat.notFound", "Chat not found"),
    "chat.uploadNotFound": ErrorDefinition("chat.uploadNotFound", "Upload not found"),
    "chat.agentUnavailable": ErrorDefinition(
        "chat.agentUnavailable",
        "This chat's Agent has been deleted or was not found. Please recreate the task.",
    ),
    "files.notFound": ErrorDefinition(
        "files.notFound", "File not found or not generated by this chat"
    ),
    "agents.notFound": ErrorDefinition("agents.notFound", "Agent not found"),
    "agents.nameExists": ErrorDefinition(
        "agents.nameExists", "Agent name already exists"
    ),
    "agents.protected": ErrorDefinition(
        "agents.protected", "Agent does not exist or is protected"
    ),
    "agents.avatarNotFound": ErrorDefinition(
        "agents.avatarNotFound", "Agent avatar not found"
    ),
    "market.searchRequired": ErrorDefinition(
        "market.searchRequired", "Search query is required"
    ),
    "market.skillExists": ErrorDefinition(
        "market.skillExists", "Skill {{skill}} is already installed"
    ),
    "market.extensionExists": ErrorDefinition(
        "market.extensionExists", "Extension {{name}} is already installed"
    ),
    "market.mcpExists": ErrorDefinition(
        "market.mcpExists", "MCP server {{name}} already exists"
    ),
    "settings.invalidTimezone": ErrorDefinition(
        "settings.invalidTimezone", "Timezone must be a valid IANA timezone"
    ),
    "usage.invalidRange": ErrorDefinition(
        "usage.invalidRange", "Usage range cannot exceed 90 days"
    ),
    "request.invalid": ErrorDefinition(
        "request.invalid", "The request could not be processed"
    ),
    "server.error": ErrorDefinition(
        "server.error", "The server could not complete the request"
    ),
}

_EXACT_CODES = {definition.message: code for code, definition in ERROR_CODES.items()}
_DYNAMIC_PATTERNS: tuple[tuple[re.Pattern[str], str, tuple[str, ...]], ...] = (
    (
        re.compile(r"^Skill (.+) is already installed$"),
        "market.skillExists",
        ("skill",),
    ),
    (
        re.compile(r"^Extension (.+) is already installed$"),
        "market.extensionExists",
        ("name",),
    ),
    (re.compile(r"^MCP server (.+) already exists$"), "market.mcpExists", ("name",)),
    (re.compile(r"^Chat (.+) not found$"), "chat.notFound", ("id",)),
)


def classify_error(detail: Any, status_code: int) -> tuple[str, dict[str, Any], str]:
    """Return a stable code, interpolation params, and legacy message."""

    message = str(detail)
    exact = _EXACT_CODES.get(message)
    if exact:
        return exact, {}, message
    for pattern, code, names in _DYNAMIC_PATTERNS:
        match = pattern.match(message)
        if match:
            return code, dict(zip(names, match.groups())), message
    return ("server.error" if status_code >= 500 else "request.invalid"), {}, message


def error_payload(detail: Any, status_code: int) -> dict[str, Any]:
    code, params, message = classify_error(detail, status_code)
    return {"detail": message, "code": code, "params": params}
